services:
  # Backend Service
  - type: web
    name: furniture-backend
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./quan-ly-noi-that-backend/Dockerfile
    dockerContext: ./quan-ly-noi-that-backend
    healthCheckPath: /actuator/health
    
    buildFilter:
      paths:
        - quan-ly-noi-that-backend/**
        
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://qlnt-api-server-2025.database.windows.net:1433;database=qlnt_db_azure;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: APPLICATION_SECURITY_JWT_SECRET_KEY
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: furniture-frontend
          envVarKey: RENDER_EXTERNAL_URL

  # Frontend Service
  - type: web
    name: furniture-frontend
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./quan-ly-noi-that-frontend/Dockerfile
    dockerContext: ./quan-ly-noi-that-frontend
    healthCheckPath: /health
    
    buildFilter:
      paths:
        - quan-ly-noi-that-frontend/**
        
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: furniture-backend
          property: url