services:
  - type: web
    name: furniture-backend
    runtime: docker
    plan: free
    # Giữ nguyên cấu hình buildContext và dockerfilePath
    dockerfilePath: quan-ly-noi-that-backend/Dockerfile
    buildContext: quan-ly-noi-that-backend
    buildFilter:
      paths:
        - quan-ly-noi-that-backend/**
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://103.199.36.147:1433;databaseName=qlnt_db;encrypt=false
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: nhacc123@